runtime: custom
api_version: '1.0'
env: flexible
env_variables:
  REACT_APP_SERVER_URL: 'https://server-uhvpqm6sra-uc.a.run.app'
manual_scaling:
  instances: 1
service_account: project13-131313@appspot.gserviceaccount.com
