# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild_basic_config]
steps:
  # [START cloudbuild_server_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/server:${COMMIT_SHA}', './server']
  # [END cloudbuild_server_image_yaml]
  # [START cloudbuild_client_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/client:${COMMIT_SHA}', './client']
  # [END cloudbuild_client_image_yaml]


  # [START cloudbuild_server_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/server:${COMMIT_SHA}']
  # [END cloudbuild_server_push_yaml]
  # [START cloudbuild_client_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/client:${COMMIT_SHA}']
  # [END cloudbuild_client_push_yaml]


  # [START cloudbuild_server_deploy_yaml]
  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'server-${COMMIT_SHA}',
           '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/server:${COMMIT_SHA}',
           '--region', 'us-central1', '--platform', 'managed',
           '--port', '5000',
           '--allow-unauthenticated']
  # [END cloudbuild_server_deploy_yaml]
  # [START cloudbuild_server_deploy_yaml]
  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'client-${COMMIT_SHA}',
           '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/client:${COMMIT_SHA}',
           '--region', 'us-central1', '--platform', 'managed',
           '--port', '3000',
           '--allow-unauthenticated']
  # [END cloudbuild_server_deploy_yaml]
